#!/usr/bin/env bash
set -euo pipefail

# Contract for the delivery orchestrator:
#   {
#     "detected": true|false,
#     "artifact_text": "normalized text artifact",
#     "vendors": ["coderabbit", "qodo"],
#     "comments": [...]
#   }

pr_number="${1:-}"

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI is required." >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required." >&2
  exit 1
fi

if [[ -z "$pr_number" ]]; then
  pr_number="$(gh pr view --json number -q .number)"
fi

repo="$(gh repo view --json nameWithOwner -q .nameWithOwner)"
pr_json="$(gh pr view "$pr_number" --json number,title,url,headRefName,baseRefName,isDraft,state,comments,reviews)"

review_comments_json="$(
  gh api --paginate "repos/$repo/pulls/$pr_number/comments?per_page=100" \
    --jq '.[]'
)"

if [[ -n "$review_comments_json" ]]; then
  review_comments_json="$(printf '%s\n' "$review_comments_json" | jq -s '.')"
else
  review_comments_json='[]'
fi

jq -n \
  --argjson pr "$pr_json" \
  --argjson review_comments "$review_comments_json" '
    def normalize_text:
      tostring
      | gsub("\r"; "")
      | gsub("\\s+"; " ")
      | ascii_downcase;

    def author_login:
      (.author.login // .user.login // "unknown");

    def author_type:
      (.author.type // .user.type // "unknown");

    def body_text:
      (.body // "");

    def looks_like_ai_identity:
      (author_login | ascii_downcase) as $login
      | (author_type | ascii_downcase) as $type
      | ($login | test("qodo|coderabbit|copilot|code-review|ai[-_]?review|review[-_]?bot"))
        or ($type == "bot" and ($login | test("copilot|rabbit|review|ai|qodo")));

    def looks_like_ai_text:
      (body_text | normalize_text) as $body
      | ($body | test("ai code review|automated code review|generated by|copilot|coderabbit|code rabbit|qodo|review bot|suggestion:"));

    def vendor_name:
      (author_login | ascii_downcase) as $login
      | (body_text | normalize_text) as $body
      | if ($login | test("coderabbit")) or ($body | test("coderabbit|code rabbit")) then "coderabbit"
        elif ($login | test("qodo")) or ($body | test("qodo")) then "qodo"
        elif ($login | test("copilot")) or ($body | test("copilot")) then "copilot"
        elif looks_like_ai_identity or looks_like_ai_text then
          if $login != "unknown" then $login else "generic-ai-review" end
        else null
        end;

    def comment_kind($channel):
      (body_text | normalize_text) as $body
      | if $channel == "inline_review" then "finding"
        elif ($body | test("summary|overall|overview|high level|high-level|general feedback|looks good|no major issues|quick recap")) then "summary"
        elif ($body | test("should|could|must|consider|missing|bug|issue|incorrect|guard|handle|return|null|undefined|race|rename|suggestion:|nit:|nitpick")) then "finding"
        else "unknown"
        end;

    def review_entry($channel; $path; $line):
      (vendor_name) as $vendor
      | if $vendor == null then
          empty
        else
          {
            vendor: $vendor,
            channel: $channel,
            author_login: author_login,
            author_type: author_type,
            body: body_text,
            path: $path,
            line: $line,
            url: (.html_url // .url // ""),
            updated_at: (.updated_at // .submittedAt // .updatedAt // .createdAt // ""),
            kind: comment_kind($channel)
          }
        end;

    ($pr.comments // [])
    | map(review_entry("issue_comment"; null; null)) as $issue_comments
    | ($pr.reviews // [])
    | map(review_entry("review_summary"; null; null)) as $review_summaries
    | $review_comments
    | map(review_entry("inline_review"; (.path // null); (.line // .original_line // null))) as $inline_comments
    | ($issue_comments + $review_summaries + $inline_comments) as $matches
    | ($matches | map(.vendor) | unique | sort) as $vendors
    | {
        detected: ($matches | length > 0),
        artifact_text:
          (
            [
              "PR #\($pr.number): \($pr.title)",
              "URL: \($pr.url)",
              "Branch: \($pr.headRefName) -> \($pr.baseRefName)",
              "State: \($pr.state)\(if $pr.isDraft then " (draft)" else "" end)",
              "Detected AI review comments: \($matches | length)",
              "Vendors: \(if ($vendors | length) > 0 then ($vendors | join(", ")) else "none" end)",
              ""
            ]
            + (
              $matches
              | map(
                  "- [\(.kind)][\(.vendor)][\(.channel)] \(.author_login)"
                  + (if .path then " on \(.path):\(.line // 0)" else "" end)
                  + (if .updated_at != "" then " at \(.updated_at)" else "" end)
                  + "\n  "
                  + (.body | gsub("\r"; "") | gsub("\n"; "\n  "))
                  + (if .url != "" then "\n  \(.url)" else "" end)
                )
            )
          ) | join("\n"),
        vendors: $vendors,
        comments: $matches
      }
  '
