#!/usr/bin/env bash
set -euo pipefail

# Contract for the delivery orchestrator:
#   {"detected":true|false,"artifact":"normalized text artifact"}

pr_number="${1:-}"

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI is required." >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required." >&2
  exit 1
fi

if [[ -z "$pr_number" ]]; then
  pr_number="$(gh pr view --json number -q .number)"
fi

repo="$(gh repo view --json nameWithOwner -q .nameWithOwner)"
pr_json="$(gh pr view "$pr_number" --json number,title,url,headRefName,baseRefName,isDraft,state,comments,reviews)"

review_comments_json="$(
  gh api --paginate "repos/$repo/pulls/$pr_number/comments?per_page=100" \
    --jq '.[]'
)"

if [[ -n "$review_comments_json" ]]; then
  review_comments_json="$(printf '%s\n' "$review_comments_json" | jq -s '.')"
else
  review_comments_json='[]'
fi

artifact="$(
  jq -n \
    --argjson pr "$pr_json" \
    --argjson review_comments "$review_comments_json" '
      def normalize_text:
        tostring
        | gsub("\r"; "")
        | gsub("\\s+"; " ")
        | ascii_downcase;

      def looks_like_ai_identity:
        (.user.login // "" | ascii_downcase) as $login
        | (.user.type // "" | ascii_downcase) as $type
        | ($login | test("qodo|coderabbit|copilot|code-review|ai[-_]?review|review[-_]?bot"))
          or ($type == "bot" and ($login | test("copilot|rabbit|review|ai|qodo")));

      def looks_like_ai_text:
        (.body // "" | normalize_text) as $body
        | ($body | test("ai code review|automated code review|generated by|copilot|coderabbit|qodo|review bot|suggestion:"));

      def review_entry($kind; $path; $line):
        {
          kind: $kind,
          author: (.user.login // "unknown"),
          body: (.body // ""),
          url: (.html_url // ""),
          updated_at: (.updated_at // ""),
          path: $path,
          line: $line
        };

      def matches_ai_review:
        looks_like_ai_identity or looks_like_ai_text;

      ($pr.comments // [])
      | map(select(matches_ai_review) | review_entry("issue"; null; null)) as $issue_comments
      | ($pr.reviews // [])
      | map(select(matches_ai_review) | review_entry("review-summary"; null; null)) as $review_summaries
      | $review_comments
      | map(select(matches_ai_review) | review_entry("inline"; (.path // null); (.line // .original_line // null))) as $inline_comments
      | ($issue_comments + $review_summaries + $inline_comments) as $matches
      | {
          matches: $matches,
          artifact:
            (
              [
                "PR #\($pr.number): \($pr.title)",
                "URL: \($pr.url)",
                "Branch: \($pr.headRefName) -> \($pr.baseRefName)",
                "State: \($pr.state)\(if $pr.isDraft then " (draft)" else "" end)",
                "",
                "Detected AI review comments: \($matches | length)"
              ]
              + (
                $matches
                | map(
                    "- [\(.kind)] \(.author)"
                    + (if .path then " on \(.path):\(.line // 0)" else "" end)
                    + (if .updated_at != "" then " at \(.updated_at)" else "" end)
                    + "\n  "
                    + (.body | gsub("\r"; "") | gsub("\n"; "\n  "))
                    + (if .url != "" then "\n  \(.url)" else "" end)
                  )
              )
            ) | join("\n")
        }
    ' 
)"

detected="$(echo "$artifact" | jq '.matches | length > 0')"
normalized_artifact="$(echo "$artifact" | jq -r '.artifact')"

jq -n \
  --argjson detected "$detected" \
  --arg artifact "$normalized_artifact" \
  '{detected: $detected, artifact: $artifact}'
